sensors:
  RadarIfxAvian_00:
    _target_: ifxdaq.sensor.radar_ifx.RadarIfxAvian
    device_id: 00323153-4e46-3243-3039-303131303335
    config_file: D:/projects/examples/radar_configs/RadarIfxBGT60.json
  CamOpenCV_00:
    _target_: ifxdaq.sensor.camera_ocv.CamOpenCV
    device_id: '0'
    config_file: D:/projects/CamOpenCV_00.json
  RadarIfxAvian_01:
    _target_: ifxdaq.sensor.radar_ifx.RadarIfxAvian
    device_id: 00323153-4e46-3243-3039-303131303530
    config_file: D:/projects/RadarIfxAvian_01.json
